### ISSUE TITLE
Connect ctldap over docker network

### ISSUE THREAD

**Issue by sim-san** [milux/ctldap#34]
I conntect the ctlap to an other docker container with an docker network.
I get this error by testing the ldap with ldapsearch.

```
ChurchTools-LDAP-Wrapper listening @ ldap://0.0.0.0:1389
[DEBUG] churchtools - Admin bind DN: cn=root, ou=users, o=churchtools
[DEBUG] churchtools - Authentication success
[DEBUG] churchtools - SEARCH base object: ou=users, o=churchtools scope: sub
[DEBUG] churchtools - Filter: (objectclass=*)
[DEBUG] churchtools - Search for users
[DEBUG] churchtools - Performing request to API function getUsersData
[ERROR] churchtools - Error while retrieving users:
TypeError: Cannot read property '0' of undefined
    at /app/ctldap.js:263:28
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```

Can you help me ?

**Comment by sim-san** [comment]
This was a network connection isue
